//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateAuthorization : ICloneable
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }

        public object Clone()
        {
            return new DateAuthorization
            {
                id = this.id,
                Email = this.Email,
                Password = this.Password,
                User = (User)this.User.Clone()
            };
        }
    }
}
