//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.GoodSales = new HashSet<GoodSale>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int SubcategoriesId { get; set; }
        public decimal Price { get; set; }
        public int UnitId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodSale> GoodSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
